name: PR checks

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run cypress:ci
