name: Storybook snapshots

on:
  push:
    # update etalon screenshots for Percy
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  storybook-snapshots:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build-storybook
    - run: npm run storybook:snapshot
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
